<?php
/**
 * - Main "foreach" loop is based on: \BASE\DEFAULT\template\catalog\product\list.phtml
 *   with some small changes:
 *		- h2 replaced with h3
 */
?>
<?php
	$_productCollection = $this->getLoadedProductCollection();
?>
<?php if ($_productCollection && ($_collectionSize = $_productCollection->count())): ?>
<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('jewelry');
	$labelsHelper = $this->helper('jewelry/labels');
	$templateHelper = $this->helper('jewelry/template');
	
	//Default image size
	$imgWidth = 168;
	$imgHeight = 168;
	
	//Modify slider depending on number of slides
	$sliderClasses = '';
	if($_collectionSize > 0)
	{
		if($_collectionSize <= 5)
			$sliderClasses .= " count-$_collectionSize";
		else
			$sliderClasses .= " count-multi";
	}
	
	//Create random value
	list($usec, $sec) = explode(' ', microtime());
	//$randomSeed = ;
    mt_srand( (float) $sec + ((float) $usec * 100000) );
    $r = mt_rand();
?>
<h3 class="section-title" ><?php echo $this->getBlockName(); ?></h3>
<div class="itemslider-wrapper itemslider-wrapper-<?php echo $r; ?>">

	<div class="nav-wrapper gen-slider-arrows1 gen-slider-arrows1-pos-top-right"></div>
    
    <div class="itemslfp itemslider-horizontal itemslider-x<?php if($sliderClasses) echo $sliderClasses; ?>">
        <ul class="lfp">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item">
                    <div class="nx_product_image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
                    
                        <img src="<?php echo $theme->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                        
                        <?php if ($theme->getCfg('category/alt_image')): ?>
							<?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
						<?php endif; ?>                        
                        <?php //Product labels
							//echo $labelsHelper->getLabels($_product); ?>
							                    
                    </a>
					</div>			
                    
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    
                     <?php echo $this->getReviewsSummaryHtml($_product, "short", true); //reviews ?>
                    <div>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                        
                        	<?php if ($this->getHideButton() == false): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></button>
                            <?php endif; ?>
                            
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>

                    	<?php //Add-to links
						if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
						{
							if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
								echo $templateHelper->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-textlink display-onhover');
							else //Always display
								echo $templateHelper->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-textlink');
						}
						?>
                    </div>
                    <div class="PricediscountAmount"><img src="<?php echo $this->getSkinUrl('images/Feature.png', array('_secure'=>false))  ?>">
                     </div>
                </li>
            <?php endforeach; ?>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider -->
<div style="clear: both;"></div>
</div> <!-- end: itemslider-wrapper -->
<?php endif; ?>
