<?php
/**
 * - Main "foreach" loop is based on: \BASE\DEFAULT\template\catalog\product\list.phtml
 *   with some small changes:
 *		- h2 replaced with h3
 */
?>
<?php
	$_productCollection = $this->getLoadedProductCollection();
?>
<?php if ($_productCollection && ($_collectionSize = $_productCollection->count())): ?>
<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('jewelry');
	$labelsHelper = $this->helper('jewelry/labels');
	$templateHelper = $this->helper('jewelry/template');
	
	//Default image size
	$imgWidth = 168;
	$imgHeight = 168;
	
	$sliderClasses = '';
	if($_collectionSize > 0)
	{
		if($_collectionSize <= 5)
			$sliderClasses .= " count-$_collectionSize";
		else
			$sliderClasses .= " count-multi";
	}
	//Create random value
	list($usec, $sec) = explode(' ', microtime());
	//$randomSeed = ;
    mt_srand( (float) $sec + ((float) $usec * 100000) );
    $r = mt_rand();
?>

<h3 class="section-title" >Promotion products</h3>
<div class="itemslider-wrapper itemslider-wrapper-<?php echo $r; ?>">

	<div class="nav-wrapper gen-slider-arrows1 gen-slider-arrows1-pos-top-right"></div>
    
    <div class="itemslider itemslider-horizontal itemslider-x<?php if($sliderClasses) echo $sliderClasses; ?>" >
        <ul class="slides products-grid">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item" >
                	<div class="img-promotion">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
                        <img src="<?php echo $theme->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                                            
                    </a>
					</div>					
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    <div class="nx-rating"  >
                    <?php echo $this->getReviewsSummaryHtml($_product, "short", true); //reviews ?>
                                    
                    </div>
                    <div style="margin-left:-10px; padding:0px;"><?php  echo $this->getPriceHtml($_product, true) ?></div>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                        
                        	<?php if ($this->getHideButton() == false): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></button>
                            <?php endif; ?>
                            
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>

                    	<?php //Add-to links
						if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
						{
							if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
								echo $templateHelper->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-textlink display-onhover');
							else //Always display
								echo $templateHelper->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-textlink');
						}
						?>
                    </div>
                    <div class="nx-hover" style="display:none;">
                    <div class="nbx-products-image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
                        <img src="<?php echo $theme->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                    </a>
					</div>					
                    <p class="nbx-title-product"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
                    <div class="nbx-rating"  >
                    <?php echo $this->getReviewsSummaryHtml($_product, "short", true); //reviews ?>
                                    
                    </div> 
                    <div class="nbx-price-product"><div style="clear:both;"></div>
                    <?php  echo $this->getPriceHtml($_product, true) ?>                    
                    </div>  
                    <div class="add-new">
                    <div class="addtocart-area">
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span>Add to cart</span></button>
                      
                    </div>
                    <div class="nx-detail"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" >Detail</a></div>                 
                    </div>
                    </div>                    
                    
                </li>
            <?php endforeach; ?>
        </ul> <!-- end: slides -->
    </div> <!-- end: itemslider -->

</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
	jQuery(function($) {
		$('.itemslider-wrapper-<?php echo $r; ?> .itemslider').flexslider({
			namespace: "",
			animation: "slide",
			easing: "easeInQuart",
			
			<?php if($time = intval($theme->getCfg('product_slider/timeout'))): ?>
				slideshowSpeed: <?php echo $time; ?>,
				animationLoop: true,
			<?php else: ?>
				slideshow: false,
				animationLoop: false,
			<?php endif; ?>
			
			<?php if($speed = intval($theme->getCfg('product_slider/speed'))): ?>
				animationSpeed: <?php echo $speed; ?>,
			<?php endif; ?>
			
			pauseOnHover: true,
			controlNav: false,
			
			controlsContainer: ".itemslider-wrapper-<?php echo $r; ?> .nav-wrapper",
			//itemWidth: 196,
			itemWidth: 294.5,
			move: <?php echo intval($theme->getCfg('product_slider/move_items')); ?>
		});
	});
//]]>
</script>
<?php endif; ?>
