<?php $zoomHelper = $this->helper('cmsmart_productzoom'); ?>
<?php if($zoomHelper->useLightbox()): ?>
	<?php
		$maxWidth	= $zoomHelper->getCfg('lightbox/max_width');
		$maxHeight	= $zoomHelper->getCfg('lightbox/max_height');
		$cfg = '';
		if ($maxWidth)
			$cfg .= ", maxWidth:'{$maxWidth}'";
		if ($maxHeight)
			$cfg .= ", maxHeight:'{$maxHeight}'";
	?>
	<script type="text/javascript">
        jQuery(function($) {
            
            $(".lightbox-group").colorbox({
			<?php if ($zoomHelper->getCfg('lightbox/group')): ?>
                rel:		'lightbox-group',
			<?php endif; ?>
                opacity:	0.5,
                speed:		300,
                current:	'<?php echo $this->__('image {current} of {total}') ?>'
				<?php if ($cfg) echo $cfg; ?>
			});
			
			<?php if ($zoomHelper->getCfg('lightbox/group')): ?>
				$(".product-zoom-gallery").first().removeClass("cboxElement");
			<?php endif; ?>            
			
			$(".product-zoom-gallery").click(function() {
				$("#zoom-btn").prop('href', $(this).prop('href'));
			
				<?php if ($zoomHelper->getCfg('lightbox/group')): ?>
					$(".product-zoom-gallery").each(function() {
						$(this).addClass("cboxElement");
					});
					$(this).removeClass("cboxElement");
				<?php endif; ?>
			});
            
        });
    </script>
<?php endif; ?>