<div class="b-index" style="margin-right: 0px  !important;">
<h6 class="heading"><?php echo Mage::getStoreConfig('video/videobug/title_block_fb') ; ?></h6>
<?php //echo Mage::getStoreConfig('video/videobug/link_fb') ; ?>
<div><iframe style="overflow: hidden; width: 305px; height: 300px;" src="http://www.facebook.com/plugins/likebox.php?href=<?php echo Mage::getStoreConfig('video/videobug/link_fb') ; ?>?fref=ts&amp;locale=en_US&amp;width=290&amp;colorscheme=light&amp;show_faces=1&amp;border_color=%23e4e4e5&amp;stream=0&amp;header=0&amp;height=280" frameborder="0" scrolling="no" width="305" height="282"></iframe></div>
</div>