<?php
/**
 * Block of categories
 */
?>
<?php
	$theme = $this->helper('jewelry');
	$visibilityClass = $theme->getCfg('category/categories_hide_on_mobile') ? 'hide-below-768' : '';
?>
<?php if ($theme->getCfg('category/categories')): ?>
<div class="block block-vertnav<?php echo " $visibilityClass"; ?>">
	<div class="block-title">
		<strong><span><?php echo $this->__('Categories'); ?></span></strong>
	</div>
	<div class="block-content">

		<ul class="accordion vertnav clearer">
			<?php echo $this->renderCategoriesMenuHtml(TRUE, 0,'level-top'); ?>
		</ul>
    </div>
</div>
<?php endif; ?>